### ISSUE TITLE
Issues with various guns

### ISSUE THREAD

**Issue by the-red-soul** [Leviathan143/minecraft-quiverbow#14] opened 2021-02-02 06:37 UTC
The ender bow will NOT let you fire again until you pickup the arrow that you shot with it. If the arrow hits a mob and dissapears you can no longer fire the bow.

Sunray recharges if on the overworld surface during night even tho it technically should not

Four headed dragonbox by default fires 54 projectiles. Probably fat fingered config.

A couple guns have sound issues when firing. Most notable are sugar engine and lapis coil

Modded coin tosser by default should fire 4 nuggets instead of 3

A few guns that fire multiple projectiles still only consume one ammunition rendering them quite overpowered. Such as the Snowball cannon, firing 4 snowballs but using one ammo, 4 Headed dragonbox, Coin tosser/modded coin tosser, seedling, seed sweeper, nether bellows, redstone sprayer, probably a couple others

The guns are not dropping their clips upon becoming empty.

I will thank you for what you did to sunray. It needed that rework a lot.

Jar im using from curseforge 

![image](https://user-images.githubusercontent.com/31638088/106561861-b2cd8080-64e6-11eb-9d15-a2451bf69dd0.png)

**Comment by Daomephsta** [comment] 2021-02-02 08:10
When reporting bugs, each bug should be a separate issue. This applies to any issue tracker. Since issues are closed when the bug is fixed, combining unrelated bugs into one issue makes it harder to track what's fixed and what's not. 

> The ender bow will NOT let you fire again until you pickup the arrow that you shot with it. If the arrow hits a mob and dissapears you can no longer fire the bow.

I can't reproduce this in 0.3.0. It's possible you're experiencing the bug where it consumes all arrows in a stack, instead of 1. That's fixed in dev.

> A couple guns have sound issues when firing. Most notable are sugar engine and lapis coil

This is too vague, you need to be clearer about what sound issues you're encountering. Please create a new issue with more information.

> I will thank you for what you did to sunray. It needed that rework a lot.

I assume you mean the beacon-style beam? The damage is ridiculous in 0.3.0, it's been turned down in dev.

The following issues are definitely resolved in dev:
> * Sunray recharges if on the overworld surface during night
> * Four headed dragonbox by default fires 54 projectiles
> * Snowball Cannon, 4 Headed Dragonbox, Seed Sweeper, Nether Bellows, & Redstone Sprayer ammo consumption. The Seedling only fires 1 projectile, so 1 ammo consumption is correct. 

I've created issues for everything else that needs fixing, so I'm closing this issue.

**Closed as completed by Daomephsta** 2021-02-02 08:10 UTC

**Comment by Daomephsta** [comment] 2021-02-04 08:55
@the-red-soul 
You still need to create an issue with more detail on the sound problems you're experiencing
